apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.auth.replicas }}

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
      - name: auth
        image: {{ .Values.auth.image }}
        imagePullPolicy: Always

        resources:
{{ toYaml .Values.auth.resources | indent 10 }}

        ports:
        - containerPort: 8001

        livenessProbe:
          httpGet:
            path: /docs
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /docs
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret