apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}

data:
  POSTGRES_HOST: "postgres"
  POSTGRES_DB: "ai_platform"
  POSTGRES_USER: "admin"

  REDIS_HOST: "redis"

  RABBITMQ_HOST: "rabbitmq"

  JWT_ALGORITHM: "HS256"
