apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}

data:
  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}

  REDIS_HOST: {{ .Values.config.redisHost | quote }}

  RABBITMQ_HOST: {{ .Values.config.rabbitmqHost | quote }}

  JWT_ALGORITHM: {{ .Values.config.jwtAlgorithm | quote }}
