apiVersion: apps/v1
kind: Deployment

metadata:
  name: ollama
  namespace: {{ .Release.Namespace }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ollama

  template:
    metadata:
      labels:
        app: ollama

    spec:
      containers:
      - name: ollama
        image: {{ .Values.ollama.image }}

        ports:
        - containerPort: 11434

        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama

      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-pvc