apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: uploads-pvc
  namespace: {{ .Release.Namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
