apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.worker.replicas }}

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
      - name: worker
        image: {{ .Values.worker.image }}
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret

        volumeMounts:
        - name: uploads
          mountPath: /app/uploads

        - name: uploads
          mountPath: /app/generated_files

      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc