api:
  image: cherroman/api:latest
  replicas: 1

auth:
  image: cherroman/auth:latest
  replicas: 1

frontend:
  image: cherroman/frontend:latest
  replicas: 1

worker:
  image: cherroman/worker:latest
  replicas: 1

ingress:
  enabled: true
  appHost: app.local
  apiHost: api.local
  authHost: auth.local

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

postgres:
  image: postgres:16

redis:
  image: redis:7

rabbitmq:
  image: rabbitmq:3-management

ollama:
  image: ollama/ollama

secret:
  postgresPassword: CHANGE_ME
  jwtSecret: CHANGE_ME

config:
  postgresHost: postgres
  postgresDb: ai_platform
  postgresUser: admin

  redisHost: redis

  rabbitmqHost: rabbitmq

  jwtAlgorithm: HS256