api:
  image: cherroman/api:latest
  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi

auth:
  image: cherroman/auth:latest
  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  image: cherroman/frontend:latest
  replicas: 1

  resources:
    requests:
      cpu: 50m
      memory: 64Mi

    limits:
      cpu: 200m
      memory: 256Mi

worker:
  image: cherroman/worker:latest
  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  appHost: app.local
  apiHost: api.local
  authHost: auth.local

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

postgres:
  image: postgres:16

  resources:
    requests:
      cpu: 250m
      memory: 256Mi

    limits:
      cpu: "1"
      memory: 1Gi

redis:
  image: redis:7

  resources:
    requests:
      cpu: 50m
      memory: 64Mi

    limits:
      cpu: 200m
      memory: 256Mi

rabbitmq:
  image: rabbitmq:3-management

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi

ollama:
  image: ollama/ollama

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

    limits:
      cpu: "2"
      memory: 4Gi

secret:
  postgresPassword: CHANGE_ME
  jwtSecret: CHANGE_ME

config:
  postgresHost: postgres
  postgresDb: ai_platform
  postgresUser: admin

  redisHost: redis

  rabbitmqHost: rabbitmq

  jwtAlgorithm: HS256